[package]
name = "guhiki"
version = "0.1.0"
authors = ["SyS <sreyassreelal@gmail.com>"]
edition = "2018"
build = "build.rs" 

[dependencies]
lalrpop-util = "0.18.1"
clap = "2.33"

[build-dependencies]
lalrpop = "0.18"

[profile.release]
lto = true